[package]
name = "sudoku-ak-unique-cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cust = "0.2.2"
itertools = "0.10.3"
static_assertions = "0.1.1"
rand = "0.8.4"
